# Site settings
title: Digital Public Square
email: hello@digitalpublicsquare.org
description: >- # this means to ignore newlines until "baseurl:"
  DPS's official GIT repository for our misinformation games and tools 
  - you'll find their Privacy Policy, Terms of Use, and repositories 
  here so you can track any changes over time.
baseurl: "/antimisinfogames"
url: "https://digitalpublicsquare.github.io"
github_username: digitalpublicsquare
github_url: https://github.com/digitalpublicsquare/antimisinfogames

# Build settings
markdown: kramdown
theme: minima
blog: false
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
