# Site settings
title: Made by Goodbit
author: Goodbit
email: hello@madebygoodbit.com
description: >- # this means to ignore newlines until "baseurl:"
  Goodbit's official GIT repository for our games and tools 
  - you'll find their Privacy Policy, Terms of Use, and repositories 
  here so you can track any changes over time.
baseurl: "/policies"
url: "https://madebygoodbit.github.io/"
github_username: madebygoodbit
github_url: https://github.com/madebygoodbit/policies

# Build settings
markdown: kramdown
theme: minima
blog: false
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
